### ISSUE TITLE
Warning: array_key_exists() expects parameter 2 to be array, null given on line 262, 268, 271, 274

### ISSUE THREAD

**Issue by ehumps** [jimok82/MiningPoolHubStats#1]
https://github.com/jimok82/MiningPoolHubStats/blob/30e38d71f9dde2743fd030e90b7fd855d5f29aab/minerstats.php#L262

Stats page is throwing the warning in the title of this issue. I don't think $payout_coins is being defined anywhere.

**Comment by jimok82** [comment]
Fixed. good catch
