### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by ajkis** [jimok82/MiningPoolHubStats#2]
I tried both entering API FIAT in code and URL.

Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/html/minerstats.php:83 Stack trace: #0 /var/www/html/minerstats.php(91): make_api_call('https://miningp...') #1 {main} thrown in /var/www/html/minerstats.php on line 83

p.s.  If I use the site https://miningpoolhubstats.mindbrite.com it works

**Comment by jimok82** [comment]
You're missing php-curl, which is the php library that allows it to make calls to remote address
